name: Test compilation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ opam ]

    steps:

      - name: Try to restore opam cache
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: opam-${{github.base_ref}}-${{github.ref}} 
          restore-keys: |
            opam--refs/heads/${{github.base_ref}}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.07.1

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: opam repo add coq-released https://coq.inria.fr/opam/released
      - run: opam install coq.8.12.1 coq-equations.1.2.3+8.12 coq-stdpp.1.4.0 coq-metacoq-checker.1.0~beta1+8.12

      - run: opam exec -- make -j 2 
